out_dir: "./out/predictor"
name: "recurrent-net"
data:
  datasets:
    - house_data_file: './res/data/opsd_building_1.csv'
      name: 'opsd_building_1'
    - house_data_file: './res/data/opsd_building_3.csv'
      name: 'opsd_building_3'
    - house_data_file: './res/data/opsd_building_4.csv'
      name: 'opsd_building_4'
    - house_data_file: './res/data/opsd_building_6.csv'
      name: 'opsd_building_6'
  price_data_file: './res/data/ee_prices.csv'
  data_format: 'csv'
  label: 'pv'
  building:
    eval:
      - name: 'opsd_building_6'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
    test:
      - name: 'opsd_building_6'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
  price:
    eval:
      - name: 'belgium'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'denmark_west'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'denmark_east'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'france'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'netherlands'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'norway'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'sweden'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'switzerland'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'czech_republic'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'germany'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'italy'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'slovenia'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'hungary'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
    test:
      - name: 'belgium'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'denmark_west'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'denmark_east'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'france'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'netherlands'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'norway'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'sweden'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'switzerland'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'czech_republic'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'germany'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'italy'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'slovenia'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'hungary'
        periods:
          - start_date: 1514761200
            end_date: 1523224800

model:
  name: 'predictor'
  predictor_type: 'recurrent_net'
  action: 'tune'
  sequence_length: 96
  prediction_steps: 96
  n_trials: 128
  n_startup_trials: 8
  n_jobs: 1
  n_gpus: 1
  sampler: 'tpe'
  two_d: False
  seed: 42
  kwargs:
    early_stopping: True
    epochs: 200
    patience: 10
    batch_size: 64
    horizon: 96