out_dir: "./out"
name: "mpc_retrain_predictor_time_mixer"
n_eval_runs: 1
data:
  datasets:
    - name: "opsd_building_6"
      house_data_file: "./res/data/opsd_building_6.csv"
      price_data_column: 'germany'
  price_data_file: "./res/data/ee_prices.csv"
  data_format: "csv"
model:
  name: 'mpc'
  mpc_type: 'retrain_predictor'
  load:
    predictor_type: 'time_mixer'
    predictor_path: './out/predictor/time-mixer/20250206_205215/predictor.pkl'
    scaler_path: './out/predictor/time-mixer/20250206_205215/scaler.pkl'
    two_d: False
    kwargs:
      device: 'cuda:1'
      batch_size: 64
      epochs: 1
      early_stopping: False
      verbose: True
  pv:
    predictor_type: 'time_mixer'
    predictor_path: './out/predictor/time-mixer/20250206_205225/predictor.pkl'
    scaler_path: './out/predictor/time-mixer/20250206_205225/scaler.pkl'
    two_d: False
    kwargs:
      device: 'cuda:1'
      batch_size: 64
      epochs: 1
      early_stopping: False
      verbose: True
  price:
    predictor_type: 'time_mixer'
    predictor_path: './out/predictor/time-mixer/20250207_084358/predictor.pkl'
    scaler_path: './out/predictor/time-mixer/20250207_084358/scaler.pkl'
    two_d: False
    kwargs:
      device: 'cuda:1'
      batch_size: 64
      epochs: 1
      early_stopping: False
      verbose: True
  history_length: 96
  prediction_length: 96
  retrain_interval: 96
environment:
  battery:
    efficiency: 0.95
    capacity: 20000
    max_power: 8000
  scaling_method: "none"
  random_time_init: false
  init_time: 1514761200  # first_ts Out[2]: 1514848500, 1514848500
  episode_length: 8377200 # 1523224800-1514761200=8463600, 8463600-1*24*3600 = 8377200 (heat up is contained)
  action_space_type: "continuous"
  tax: 20
  prediction_horizon: 0
  dataset_args:
    building: "opsd_building_6"
    price: "germany"