out_dir: "./out/predictor"
name: "times-net"
data:
  datasets:
    - house_data_file: './res/data/opsd_building_1.csv'
      name: 'opsd_building_1'
    - house_data_file: './res/data/opsd_building_3.csv'
      name: 'opsd_building_3'
    - house_data_file: './res/data/opsd_building_4.csv'
      name: 'opsd_building_4'
    - house_data_file: './res/data/opsd_building_6.csv'
      name: 'opsd_building_6'
  price_data_file: './res/data/ee_prices.csv'
  data_format: 'csv'
  label: 'pv'
  building:
    eval:
      - name: 'opsd_building_6'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
    test:
      - name: 'opsd_building_6'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
  price:
    eval:
      - name: 'belgium'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'denmark_west'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'denmark_east'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'france'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'netherlands'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'norway'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'sweden'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'switzerland'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'czech_republic'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'germany'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'italy'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'slovenia'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
      - name: 'hungary'
        periods:
          - start_date: 1498860000
            end_date: 1514760300
    test:
      - name: 'belgium'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'denmark_west'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'denmark_east'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'france'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'netherlands'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'norway'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'sweden'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'switzerland'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'czech_republic'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'germany'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'italy'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'slovenia'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
      - name: 'hungary'
        periods:
          - start_date: 1514761200
            end_date: 1523224800
model:
  name: 'predictor'
  predictor_type: 'times_net'
  action: 'train_and_evaluate'
  sequence_length: 96
  prediction_steps: 96
  two_d: False
  use_time_features: True
  sin_cos_encoding: True
  seed: 42
  kwargs:
    device: 'cuda'
    early_stopping: True
    epochs: 200
    patience: 10
    batch_size: 32
    seq_len: 96
    pred_len: 96
    enc_in: 8
    c_out: 1
    freq: 't'
    embed: 'fixed'
    top_k: 2
    num_kernels: 4
    e_layers: 1
    d_model: 16
    d_ff: 16
    dropout: 0.3
    learning_rate: 0.000247984180034